name: Continuous Integration
on:
  push:
    branches: [ "master" , "l4"]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Navigate to project directory
      run: cd IT_Project_Unity/FrontEnd && ls -al      
    - run: cd IT_Project_Unity/FrontEnd && npm clean-install
    - run: cd IT_Project_Unity/FrontEnd && npm run build --if-present
