name: Continuous Integration
on:
  push:
    branches: [ "master" , "l4"]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Navigate to project directory
      run: cd IT_Project_Unity/FrontEnd && ls -al 
    - name: Setup Node.js and Python   
      uses: actions/setup-node@v3
      env:
        CI: true
        PATH: ${{ runner.tool_cache }}/python/2.7.17/x64:${{ env.PATH }}      
    - run: cd IT_Project_Unity/FrontEnd && npm install
    - run: cd IT_Project_Unity/FrontEnd && npm run build --if-present
