name: Continuous Integration
on:
  push:
    branches: [ "master" , "l4"]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Navigate to project directory
      run: cd IT_Project_Unity/Project\ FrontEnd && ls -al      
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'  
    - run: cd 'IT_Project_Unity/Project FrontEnd' && npm ci
    - run: cd 'IT_Project_Unity/Project FrontEnd' && npm run build --if-present
